source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DTDropDownListView_Example', :exclusive => true do
  pod "DTDropDownListView", :path => "../"
end

target 'DTDropDownListView_Tests', :exclusive => true do
  pod "DTDropDownListView", :path => "../"

  
end
